### PR TITLE
Handling onDidDismiss event in Modal and Alert components

### PR DESCRIPTION
**Pull request by enstain**
My suggestion is to handle callback which we usually place inside onDidDismiss
Also I find the same generic problem about exceeding call stack for NavController, I have fixed this the same way @rvdleun did

### CODE REVIEW

**Comment by stonelasley** [comment]
@enstain thank you very much for the PR. 
@rvdleun  I have merged your PR in for the call stack issue, along with one other but I received an error running tests in one of my apps. before I publish a new version I want to sort that out. I really appreciate the contributions.

**Comment by jesusbotella** [comment]
Just my two cents about handling onDidDismiss inside the mock.

It is so good because most people that will use the mocks from now on will have this sorted out without worrying, but I think it is a breaking change since some previous tests may fail when applying this PR.

If someone has code inside the callback calling any method of an instance with this, the test will fail since you are calling the callback from a different context and you should have it previously bound to the component instance. And therefore, if you come across this problem you will have to handle it yourself with something like this:

```js
const alertMock = {
  onDidDismiss: jasmine.createSpy('onDidDismiss').and.callFake(fn => fn.bind(myComponent)())
};

spyOn(myComponent.modalController, 'create').and.returnValue(alertMock);
```

What do you think? I think it should be said in the readme.
Thank you for your PR!

**Comment by enstain** [comment]
@jesusbotella Your remark is true except one point: we should not call onDidDismiss callback immediately like this `fn.bind(myComponent)()` (onDidDismiss callback will be called after `dismiss()` call), right?

By the way, I've just checked my actual tests for the application and I can say that I already have this case with calling method in "this" context, but it works fine already. Maybe I miss something, but this is my situation: 

Class `ModalService` is managing modal instances. The method `create` return new modal instance and also describe onDidDismiss callback which should call ModalService method.

(I change actual code, so just for example):
```
    public create(component: Component, data: object, opts: ModalOptions) {
        const modal = this.modalCtrl.create(component, data, opts);

        modal.onDidDismiss(() => {
            this.hideAll();
        });

        return modal;
    }

    public hideAll() {
       // the method inside ModalService which is called via onDidDismiss callback
    }
```

The following test checks how it works:

```
    it('should bind to the current context in onDidDismiss', () => {
        let modal = modalService.create(<params for the modal instance>);
        spyOn(modalService, 'hideAll');

        modal.dismiss();

        expect(modalService.hideAll).toHaveBeenCalled();
    });
```

This test is green. So could you please show a test case which is going to be red

**Comment by stonelasley** [comment]
@enstain I caused 2 conflicts if you wouldn't mind fixing them I'll merge this and release it. If you're unable I'll fix them tomorrow night. I really appreciate the PR.

**Comment by enstain** [comment]
HI @stonelasley, I've resolved this)

**Comment by jesusbotella** [comment]
Let me get an example later to see if I'm right or not ;)

It was failing to me when I tried to test inner onDidDismiss function and I came up with the solution I showed you before.

**Comment by stonelasley** [comment]
@enstain Thank you very much for the PR. @jesusbotella I'm testing this in a project I have, please let me know if it's causing you issues and we can come up with a solution.

**Pull request merged**
