### PR TITLE
Carry data in onDiddissmiss

### PR DESCRIPTION
**Pull request by Remco75**
This PR extends PR #26 with the addition of calling the calback with the given data. (and it solves #32)

### CODE REVIEW

**Comment by Remco75** [comment]
Btw, there were no tests yet for this file, so I just went ahead and added this. might be a good idea to expand the testing in the future ;-)

**Comment by stonelasley** [comment]
@Remco75 thanks a lot for the PR. Why are we adding the dist directory back to the repo?

**Comment by Remco75** [comment]
Aaah, I thought I did that on a different branch. It was for easy testing, but not really needed

**Comment by Remco75** [comment]
and its gone

**Comment by Remco75** [comment]
@stonelasley is it ok like this? Would be nice if this is merged so i can delete my fork and is the official npm version again 😀

**Comment by BrandonBabcock** [comment]
@stonelasley @Remco75 This functionality does not seem to be in the latest version. As far as I can tell, the part for ModalMock was never merged. A similar commit for AlertMock was merged when this PR was Closed, but that also seems to have been removed between versions 1.2.1 and 1.30. Is there a reason for this, or was it a mistake?

**Pull request closed without merging**
